name: iec_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  
  # ✅ Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.9
  google_sign_in: ^6.1.0
  dropdown_button2: ^2.3.9  # Example version

  # ✅ Image handling (latest and compatible)
  image_cropper: ^5.0.1
  image_picker: ^1.0.7

  # ✅ UI / Utils
  animated_text_kit: ^4.2.2
  http: ^1.1.0
  get_storage: ^2.0.3
  dropdown_textfield: ^1.1.0
  get: ^4.6.6
  uuid: ^4.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
